# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0002_auto_20171011_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Marcas'),
        ),
    ]
