# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0003_auto_20171011_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.CharField(blank=True, choices=[('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.TiposCombustibles'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Marcas'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Modelos'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.TiposVehiculos'),
        ),
    ]
