# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0005_clientes_empleados_rerservaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='no_tjcredito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
