# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0007_remove_empleados_no_tjcredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
    ]
