# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0008_remove_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='limite_credito',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='no_tjcredito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rerservaciones',
            name='cantidad_dia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rerservaciones',
            name='monto_dia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_chasis',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_placa',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tarifa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
