# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0009_auto_20171104_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='licencia',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='no_tjcredito',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='comision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='no_motor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
